# Generated by Django 5.2.8 on 2025-11-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-featured", "-created_at"]},
        ),
    ]
