# Generated by Django 5.2.8 on 2025-11-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
