# Generated by Django 5.2.8 on 2025-11-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_contactmessage_options_contactmessage_read"),
        ("core", "0002_create_admin"),
    ]

    operations = []
