# Generated by Django 5.2.8 on 2025-11-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_merge_20251113_1642"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="projects/")),
                ("live_link", models.URLField(blank=True, null=True)),
                ("github_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="contactmessage",
            options={},
        ),
        migrations.RemoveField(
            model_name="contactmessage",
            name="read",
        ),
        migrations.RemoveField(
            model_name="contactmessage",
            name="subject",
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
